config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :search, only: :index

  namespace :api do
    namespace :v1 do
      namespace :foods do
        get :search
      end
    end
  end
end

app/models/food.rb
# == Schema Information
#
# Table name: foods
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Food < ActiveRecord::Base
  validates :name, presence: true
  has_many :locations
end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id         :integer          not null, primary key
#  address    :text
#  user_id    :integer
#  food_id    :integer
#  latitude   :string
#  longitude  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Location < ActiveRecord::Base
  belongs_to :food
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string
#  gender                 :string
#  address                :text
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, :gender, :address, presence: true
  has_many :locations
end

app/controllers/api/v1/foods_controller.rb
class Api::V1::FoodsController < ApplicationController
  skip_before_action :verify_authenticity_token
  respond_to :json

  def search
    @food = Food.find_by_name(params[:q])
    @locations = []
    if @food.present?
      @locations = @food.locations
    end
    return :json => @locations
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :gender, :address, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :gender, :address, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.slim
.text-center
  h3 Selamat Datang di Ngidamapps
  hr
  = link_to "Cari", search_index_path, class: "btn btn-primary btn-main-page"
  | &nbsp;
  = link_to "Kontribusi", "#", class: "btn btn-success btn-main-page"

app/views/layouts/application.html.slim
doctype html
html lang="en" ng-app="ngidamApp"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Ngidamapps"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Ngidamapps
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Cari", search_index_path
              li= link_to "Kontribusi", "#"
              li= link_to "Hubungi Kami", "#"
            ul.nav.navbar-nav.pull-right
              - if user_signed_in?
                li= link_to "Logout", destroy_user_session_path
              - else
                li= link_to "Login", new_user_session_path
                li= link_to "Daftar", new_user_registration_path

    .container
      #page-container.row
        .col-lg-12
          = bootstrap_flash
          = yield

      footer.text-center
        p &copy; Tim Ganteng 2015

app/views/search/index.html.slim
.row ng-controller="foodsController"
  .col-md-6
    h1 Pencarian
    form ng-submit="search()" name="formPencarian"
      .input-group
        span.input-group-addon
          i.fa.fa-search
        input type="text" name="foodName" class="form-control" placeHolder="Masukkan kata kunci pencarian" ng-model="foodName" required="true"
      span class="help-block" ng-show="formPencarian['foodName'].$error.required" Wajib masukkan kata kunci

    hr

    .alert.alert-danger ng-show="errorStatus"
      strong
        i.fa.fa-warning
      span ng-bind="errorMessage"

    i.fa.fa-refresh.fa-spin ng-show="searching"

    ul.list-group
      li.list-group-item ng-repeat="result in locations"
        a href="#" target="blank"
          h4.list-group-item-heading ng-bind="result.location.address"
        p.list-group-item-text.text-muted ng-bind="result.location.address"